[Params]
cell_line = mESC
experiment= GRID
bin_size=1_000
second_cell_line=mESC
second_experiment=RADICL
sample = 
# 1,2,3...

[Paths]
source_data_prefix = 
data_prefix = 
plots_prefix = 
hic_prefix = 
learn_prefix = 

[Samples]
GRID_mESC = GSM2396700 GSM2396701
RADICL_mESC = SRR9201805 SRR9201807 SRR9201809
RADICL_mOPC = 