[All_features]

; selected most important features
num_features = count_ATAC-seq count_DNase-seq restriction_sites gc_count genes mean_cf compartment_vec repeats DNase-seq_cov
cat_features = compartment

; all features
; num_features = count_ATAC-seq count_DNase-seq count_CTCF count_H3K4me3 count_H3K27me3 count_H3K27ac count_H3K4me1 count_H3K9ac count_H3K9me3 count_H3K36me3 restriction_sites gc_count genes mean_cf compartment_vec repeats RNAseq_signal count_DRIP triplexes DNase-seq_cov
; cat_features = compartment tad loop

genomic_features = restriction_sites gc_count genes repeats triplexes
hic_features = mean_cf compartment_vec compartment tad loop 
peaks_features = count_ATAC-seq count_DNase-seq count_CTCF count_H3K4me3 count_H3K27me3 count_H3K27ac count_H3K4me1 count_H3K9ac count_H3K9me3 count_H3K36me3 count_DRIP RNAseq_signal

[Features]
; genomic, hic, peaks, all
group = all
window_size = 256_000
shift = 128_000
perc_mask = 99.9
mask_zeros = False